# Config file for automatic testing at travis-ci.org
language: python
sudo: required
dist: trusty
matrix:
    include:
        - python: 2.7
          env:
            - PYTHON=python

# python: 3.2
# env:
# PYTHON=python3

git:
    submodules: false

virtualenv:
    system_site_packages: true

before_install:
    - sudo apt-get update
    - sudo apt-get install $PYTHON-setuptools -y
    - sudo apt-get install $PYTHON-numpy -y
    - sudo apt-get install $PYTHON-matplotlib -y
    - sudo apt-get install $PYTHON-wxgtk2.9 -y
    - sudo apt-get install $PYTHON-nose -y

install:
    - sudo $PYTHON setup.py install

script:
    - nosetests

